name: Health Calculator Service CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: health-calculator-service
  PORT: 5000
  PYTHON_VERSION: '3.9'

jobs:
  code-quality:
    name: Code Quality & Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Dependencies
        run: |
          make init
      
      - name: Run Tests
        run: |
          make test
      
      - name: Check Test Coverage
        run: |
          . venv/bin/activate
          coverage run -m pytest
          coverage report --fail-under=60

  docker-build:
    name: Build Docker Image
    needs: code-quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker Image
        run: |
          make build

  deploy:
    name: Deploy to Azure Web App
    needs: [code-quality, docker-build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure WebApp Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'health-calculator-service'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./


# Gestion de la concurrence
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true